from typing import Literal

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableSequence
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from graph.chains.generation import generation_chain
from ingestion import getVectoreStoreRetriever

load_dotenv()

model = ChatOpenAI(model="gpt-5.5", temperature=0)


class AnswerCheck(BaseModel):
    """Analysis of a Answer wrt to Question."""

    isRelated: bool = Field(
        description="Check Whither the answer is related to asked question,"
        " is lf related yes, or else no "
    )


model = model.with_structured_output(AnswerCheck)

system = """
You are a AI Assistent and you need evaluate if the answer generated by LLM  is related to  questions asked 
"""
template = ChatPromptTemplate(
    [
        ("system", system),
        ("human", " Question : {question} \n\n LLM generated answer: {answer}"),
    ]
)

answer_grader = template | model

if __name__ == "__main__":
    # Testing python -m graph.chains.answer_grader

    response: AnswerCheck = answer_grader.invoke(
        {
            "question": "What is Prompt Engineeroing",
            "answer": """
        Prompt engineering is the art and science of designing and o
        ptimizing instructions (prompts) to guide AI models like LLMs to generate highly accurate, specific, and relevant responses
        """,
        }
    )

    print(response)

    response: AnswerCheck = answer_grader.invoke(
        {
            "question": "What is Prompt Engineeroing",
            "answer": """
            Redis Cache is an open-source, in-memory data store used to temporarily save frequently accessed
        information so applications can retrieve it with sub-millisecond latency.
        """,
        }
    )

    print(response)
